[package]
name = "cueblade"
description = "reserved for future use"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[dependencies]
chardetng = "1"
clap = { version = "4", features = ["derive"] }
claxon = "0.4"
encoding_rs = "0.8"
flacenc = "0.5"
metaflac = "0.2"
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
winnow = "1"

[dev-dependencies]
tempfile = "3"
assert_cmd = "2"
predicates = "3"
base64 = "0.23"
